/* Auto-generated by genmsg_cpp for file /home/loki/Documents/ros_workspace/mikrokopter/mk_msgs/srv/SetNavigation.srv */
#ifndef MK_MSGS_SERVICE_SETNAVIGATION_H
#define MK_MSGS_SERVICE_SETNAVIGATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace mk_msgs
{
template <class ContainerAllocator>
struct SetNavigationRequest_ {
  typedef SetNavigationRequest_<ContainerAllocator> Type;

  SetNavigationRequest_()
  : numofwps(0)
  {
  }

  SetNavigationRequest_(const ContainerAllocator& _alloc)
  : numofwps(0)
  {
  }

  typedef int32_t _numofwps_type;
  int32_t numofwps;


  typedef boost::shared_ptr< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mk_msgs::SetNavigationRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetNavigationRequest
typedef  ::mk_msgs::SetNavigationRequest_<std::allocator<void> > SetNavigationRequest;

typedef boost::shared_ptr< ::mk_msgs::SetNavigationRequest> SetNavigationRequestPtr;
typedef boost::shared_ptr< ::mk_msgs::SetNavigationRequest const> SetNavigationRequestConstPtr;


template <class ContainerAllocator>
struct SetNavigationResponse_ {
  typedef SetNavigationResponse_<ContainerAllocator> Type;

  SetNavigationResponse_()
  : ack(0)
  {
  }

  SetNavigationResponse_(const ContainerAllocator& _alloc)
  : ack(0)
  {
  }

  typedef int16_t _ack_type;
  int16_t ack;


  typedef boost::shared_ptr< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mk_msgs::SetNavigationResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetNavigationResponse
typedef  ::mk_msgs::SetNavigationResponse_<std::allocator<void> > SetNavigationResponse;

typedef boost::shared_ptr< ::mk_msgs::SetNavigationResponse> SetNavigationResponsePtr;
typedef boost::shared_ptr< ::mk_msgs::SetNavigationResponse const> SetNavigationResponseConstPtr;

struct SetNavigation
{

typedef SetNavigationRequest Request;
typedef SetNavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetNavigation
} // namespace mk_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::SetNavigationRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "19d7d32f9d24460da73ed48764d42b23";
  }

  static const char* value(const  ::mk_msgs::SetNavigationRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x19d7d32f9d24460dULL;
  static const uint64_t static_value2 = 0xa73ed48764d42b23ULL;
};

template<class ContainerAllocator>
struct DataType< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mk_msgs/SetNavigationRequest";
  }

  static const char* value(const  ::mk_msgs::SetNavigationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
int32 numofwps\n\
\n\
";
  }

  static const char* value(const  ::mk_msgs::SetNavigationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::SetNavigationResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "efd27fb04e2a6ce3c9ff1f47eb32e7bb";
  }

  static const char* value(const  ::mk_msgs::SetNavigationResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xefd27fb04e2a6ce3ULL;
  static const uint64_t static_value2 = 0xc9ff1f47eb32e7bbULL;
};

template<class ContainerAllocator>
struct DataType< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mk_msgs/SetNavigationResponse";
  }

  static const char* value(const  ::mk_msgs::SetNavigationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
int16 ack\n\
\n\
\n\
";
  }

  static const char* value(const  ::mk_msgs::SetNavigationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mk_msgs::SetNavigationRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.numofwps);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetNavigationRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mk_msgs::SetNavigationResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.ack);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetNavigationResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<mk_msgs::SetNavigation> {
  static const char* value() 
  {
    return "bebf409cbd73a6674c483f81f26e37d8";
  }

  static const char* value(const mk_msgs::SetNavigation&) { return value(); } 
};

template<>
struct DataType<mk_msgs::SetNavigation> {
  static const char* value() 
  {
    return "mk_msgs/SetNavigation";
  }

  static const char* value(const mk_msgs::SetNavigation&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mk_msgs::SetNavigationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bebf409cbd73a6674c483f81f26e37d8";
  }

  static const char* value(const mk_msgs::SetNavigationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mk_msgs::SetNavigationRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mk_msgs/SetNavigation";
  }

  static const char* value(const mk_msgs::SetNavigationRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<mk_msgs::SetNavigationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bebf409cbd73a6674c483f81f26e37d8";
  }

  static const char* value(const mk_msgs::SetNavigationResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<mk_msgs::SetNavigationResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mk_msgs/SetNavigation";
  }

  static const char* value(const mk_msgs::SetNavigationResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MK_MSGS_SERVICE_SETNAVIGATION_H

