(cl:in-package mk_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          GPSALTITUDE-VAL
          GPSALTITUDE
          SATSINUSE-VAL
          SATSINUSE
          NUMBEROFWPS-VAL
          NUMBEROFWPS
          CURRENTWP-VAL
          CURRENTWP
          ERRORCODE-VAL
          ERRORCODE
          FREE-VAL
          FREE
          PH-VAL
          PH
          CH-VAL
          CH
          RANGELIMIT-VAL
          RANGELIMIT
          NOSERIALLINK-VAL
          NOSERIALLINK
          TARGETREACHED-VAL
          TARGETREACHED
          MANUAL-VAL
          MANUAL
          GPSOK-VAL
          GPSOK
          MOTORSON-VAL
          MOTORSON
          FLYING-VAL
          FLYING
          LOWBAT-VAL
          LOWBAT
          CAREFREE-VAL
          CAREFREE
          ALTHLD-VAL
          ALTHLD
          FAILSAFE-VAL
          FAILSAFE
          ALTITUDE-VAL
          ALTITUDE
          FLYINGTIME-VAL
          FLYINGTIME
          BATTERY-VAL
          BATTERY
          GROUNDSPEED-VAL
          GROUNDSPEED
          HEADING-VAL
          HEADING
          COMPASSHEADING-VAL
          COMPASSHEADING
          NICK-VAL
          NICK
          ROLL-VAL
          ROLL
          RCQUALITY-VAL
          RCQUALITY
          ZSPEED-VAL
          ZSPEED
          TARGETHOLDTIME-VAL
          TARGETHOLDTIME
          GAS-VAL
          GAS
          CURRENT-VAL
          CURRENT
          USEDCAPACITY-VAL
          USEDCAPACITY
))