(cl:in-package mk_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          TOLERANCERADIUS-VAL
          TOLERANCERADIUS
          HOLDTIME-VAL
          HOLDTIME
          INDEX-VAL
          INDEX
          EVENTCHANNEL-VAL
          EVENTCHANNEL
          ALTITUDERATE-VAL
          ALTITUDERATE
          SPEED-VAL
          SPEED
          STATUS-VAL
          STATUS
          EVENTFLAG-VAL
          EVENTFLAG
          TYPE-VAL
          TYPE
          CAMANGLE-VAL
          CAMANGLE
))