(cl:in-package mk_msgs-srv)
(cl:export '(INDEX-VAL
          INDEX
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          STATUS-VAL
          STATUS
          HOLDTIME-VAL
          HOLDTIME
          ALTITUDERATE-VAL
          ALTITUDERATE
          SPEED-VAL
          SPEED
          HEADING-VAL
          HEADING
          TOLERANCERADIUS-VAL
          TOLERANCERADIUS
          EVENTCHANNEL-VAL
          EVENTCHANNEL
          EVENTFLAG-VAL
          EVENTFLAG
          TYPE-VAL
          TYPE
          CAMANGLE-VAL
          CAMANGLE
          ACK-VAL
          ACK
))