/* Auto-generated by genmsg_cpp for file /home/systems/Documents/ros_workspace/mikrokopter/mk_msgs/msg/MKCommands.msg */
#ifndef MK_MSGS_MESSAGE_MKCOMMANDS_H
#define MK_MSGS_MESSAGE_MKCOMMANDS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace mk_msgs
{
template <class ContainerAllocator>
struct MKCommands_ {
  typedef MKCommands_<ContainerAllocator> Type;

  MKCommands_()
  : header()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , gas(0)
  , height(0)
  , free(0)
  , frame(0)
  , config(0)
  {
  }

  MKCommands_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , gas(0)
  , height(0)
  , free(0)
  , frame(0)
  , config(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;

  typedef int64_t _gas_type;
  int64_t gas;

  typedef int64_t _height_type;
  int64_t height;

  typedef int64_t _free_type;
  int64_t free;

  typedef int64_t _frame_type;
  int64_t frame;

  typedef int64_t _config_type;
  int64_t config;


  typedef boost::shared_ptr< ::mk_msgs::MKCommands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mk_msgs::MKCommands_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MKCommands
typedef  ::mk_msgs::MKCommands_<std::allocator<void> > MKCommands;

typedef boost::shared_ptr< ::mk_msgs::MKCommands> MKCommandsPtr;
typedef boost::shared_ptr< ::mk_msgs::MKCommands const> MKCommandsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mk_msgs::MKCommands_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mk_msgs::MKCommands_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mk_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::MKCommands_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mk_msgs::MKCommands_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mk_msgs::MKCommands_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f41817acd269ca2b215f48e1803c89dd";
  }

  static const char* value(const  ::mk_msgs::MKCommands_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf41817acd269ca2bULL;
  static const uint64_t static_value2 = 0x215f48e1803c89ddULL;
};

template<class ContainerAllocator>
struct DataType< ::mk_msgs::MKCommands_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mk_msgs/MKCommands";
  }

  static const char* value(const  ::mk_msgs::MKCommands_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mk_msgs::MKCommands_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# between -pi to +pi\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
# between 0 to 1\n\
int64 gas\n\
\n\
#between 0 to pi\n\
int64 height\n\
\n\
#\n\
int64 free\n\
int64 frame\n\
int64 config\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::mk_msgs::MKCommands_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::mk_msgs::MKCommands_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::mk_msgs::MKCommands_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mk_msgs::MKCommands_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.gas);
    stream.next(m.height);
    stream.next(m.free);
    stream.next(m.frame);
    stream.next(m.config);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MKCommands_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mk_msgs::MKCommands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mk_msgs::MKCommands_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "gas: ";
    Printer<int64_t>::stream(s, indent + "  ", v.gas);
    s << indent << "height: ";
    Printer<int64_t>::stream(s, indent + "  ", v.height);
    s << indent << "free: ";
    Printer<int64_t>::stream(s, indent + "  ", v.free);
    s << indent << "frame: ";
    Printer<int64_t>::stream(s, indent + "  ", v.frame);
    s << indent << "config: ";
    Printer<int64_t>::stream(s, indent + "  ", v.config);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MK_MSGS_MESSAGE_MKCOMMANDS_H

